version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # Options: daily, weekly, monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Security Update]"
