version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 15s
      retries: 5

  sender:
    build: .
    command: >
      bash -c "sleep 15 && python send.py"
    depends_on:
      rabbitmq:
        condition: service_healthy

  receiver:
    environment:
      PYTHONUNBUFFERED=1
    build: .
    command: >
      bash -c "sleep 15 && python receive.py"
    depends_on:
      rabbitmq:
        condition: service_healthy
